stages:
- wordpress.org


PluginSVN:
  stage: wordpress.org
  image: registry.krone.at/captcha/wp-deploy
  before_script:
    # IMAGE from: https://github.com/ethitter/wp-org-plugin-deploy
    - export WP_ORG_RELEASE_REF=$CI_COMMIT_TAG
    - export PLUGIN_VERSION=$CI_COMMIT_TAG
    - export PLUGIN_VERSION_CLEAN=$(echo $CI_COMMIT_TAG| sed  's/v//g')
    - echo $PLUGIN_VERSION
    - echo $PLUGIN_VERSION_CLEAN
    - apt-get update && apt-get install -y php wget php-dom
    - wget -O /usr/bin/composer https://getcomposer.org/download/2.5.4/composer.phar && chmod a+rwx /usr/bin/composer
    - composer install --no-dev
    - git add -f vendor
    - rm -vfr   fastlane/ tests/
    - chmod +x ./bin/deploy.sh
  script: 
    - export WP_ORG_RELEASE_REF=$CI_COMMIT_TAG
    - export PLUGIN_VERSION=$CI_COMMIT_TAG
    - export PLUGIN_VERSION_CLEAN=$(echo $CI_COMMIT_TAG| sed  's/v//g')
    - echo $PLUGIN_VERSION
    - echo $PLUGIN_VERSION_CLEAN
    - ./bin/deploy.sh
  when: on_success
  tags:
    - docker
  except:
    - /.*beta.*/
  only:
    - /^v([0-9]+).*/

